[[plugins]]
repo    = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo    = 'Shougo/vimfiler.vim'
depends = 'unite.vim'

[[plugins]]
repo    = 'Shogo/neocomplete.vim'
if      = "has('lua')"

[[plugins]]
repo    = 'tpope/vim-markdown'
on_ft   = 'markdown'

[[plugins]]
repo    = 'lervag/vimtex'
on_ft   = 'tex'

[[plugins]]
repo    = 'cespare/vim-toml'
on_ft   = 'toml'

[[plugins]]
repo    = 'kana/vim-filetype-haskell'
on_ft   = 'haskell'

[[plugins]]
repo    = 'eagletmt/ghcmod-vim'
on_ft   = 'haskell'

[[plugins]]
repo    = 'ujihisa/neco-ghc'
on_ft   = 'haskell'

[[plugins]]
repo    = 'dag/vim2hs'
on_ft   = 'haskell'

[[plugins]]
repo    = 'thinca/vim-ref'
on_ft   = 'haskell'

[[plugins]]
repo    = 'ujihisa/ref-hoogle'
on_ft   = 'haskell'

[[plugins]]
repo    = 'ujihisa/unite-haskellimport'
on_ft   = 'haskell'
depends = 'unite.vim'

[[plugins]]
repo    = 'rust-lang/rust.vim'
on_ft   = 'rust'

[[plugins]]
repo    = 'racer-rust/vim-racer'
on_ft   = 'rust'

[[plugins]]
repo    = 'zchee/deoplete-jedi'
on_ft   = 'python'

# [[plugins]]
# repo    = 'kevinw/pyflakes-vim'
# on_ft   = 'python'
